+ History page - Admin
Akuanaksehatt/pos-nextjs pull request #9
Opened 2024-08-26 15:25 UTC by Akuanaksehatt

+ User page - Admin
+ (Adjusment) Stok on Menus page - Admin
(Please install react icon) -> npm install react-icons

2024-08-26 15:26 UTC, Akuanaksehatt reviewed
For better UI (Please install react icon) -> npm install react-icons

2024-08-27 16:29 UTC, Dimaspadma requested changes
Code integrasi nanti dipisah, nah di sini nanti tinggal manggil nama functionnya aja.

https://www.notion.so/2783f0f0c3e140d5b5f777a7e34a1e67?v=45cc770b469c418ead7893d2f0326aad&p=bc539286f7bb4456add0067b2feb5295&pm=s

2024-08-27 16:29 UTC, Dimaspadma commented on frontend/src/app/admin/histories/addHistory.js
> +        await fetch ("http://localhost:5000/products",
Ini ngga perlu dulu, nanti di bikin file terpisah

2024-08-27 16:29 UTC, Dimaspadma commented on frontend/src/app/admin/histories/deleteHistory.js
> +    async function handleDelete(productId)
Ini juga nanti masuknya integration

2024-08-27 16:29 UTC, Dimaspadma commented on frontend/src/app/admin/histories/updateHistory.js
> +    async function handleUpdate(e)
Ini nanti dipisah filenya

2024-08-27 16:33 UTC, Akuanaksehatt commented on frontend/src/app/admin/histories/addHistory.js
> +        await fetch ("http://localhost:5000/products",
sorry itu cuman buat testing UI

2024-08-27 16:33 UTC, Akuanaksehatt commented on frontend/src/app/admin/histories/deleteHistory.js
> +    async function handleDelete(productId)
shap

2024-08-27 16:34 UTC, Akuanaksehatt commented on frontend/src/app/admin/histories/updateHistory.js
> +    async function handleUpdate(e)
kurang jelas, mohon instruksi di notion

2024-08-28 14:19 UTC, Akuanaksehatt reviewed
Please take a review

2024-08-28 16:14 UTC, Dimaspadma requested changes

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/categories.js
> +    setIsMutating(true);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/categories.js
> +    setModal(false);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/categories.js
> +    setIsMutating(true);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/categories.js
> +    setModal(false);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/categories.js
> +    setIsMutating(true);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/categories.js
> +    setModal(false);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/products.js
> +    setIsMutating(true);
Ini tetap di bagian react

2024-08-28 16:14 UTC, Dimaspadma commented on frontend/src/api/products.js
> +    setModal(false);
Ini tetap di bagian react

2024-08-28 17:41 UTC, Akuanaksehatt reviewed
take review

2024-08-28 18:09 UTC, Dimaspadma approved these changes

2024-08-28 18:09 UTC, merged